name: Sync POS with Neon Database

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Sync with Neon Database
        run: |
          python manage.py migrate
          python manage.py syncdb  # Add custom management commands if needed

      - name: Deploy application
        run: |
          # Example: Deploy code to your hosting environment
          ./deploy.sh
